export default [
  {
    'carrier': 'aig',
    'carrier_name': 'American General Life Insurance Company',
    'monthly_premium': 58.82,
    'annual_premium': 680.0,
    'name': 'Select-a-Term - 30 Year  (2016)',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Plus Non-Tobacco',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'aig',
    'carrier_name': 'American General Life Insurance Company',
    'monthly_premium': 139.94,
    'annual_premium': 1680.0,
    'name': 'ROP Select-a-Term - 30 Year',
    'return_of_premium': true,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Plus Non-Tobacco',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'prudential',
    'carrier_name': 'Pruco Life Insurance Company',
    'monthly_premium': 60.57,
    'annual_premium': 673.0,
    'name': 'Term Essential 30 (',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Best',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'prudential',
    'carrier_name': 'Pruco Life Insurance Company',
    'monthly_premium': 68.13,
    'annual_premium': 757.0,
    'name': 'Term Elite 30  (',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Best',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'prudential',
    'carrier_name': 'Pruco Life Insurance Company',
    'monthly_premium': 123.42,
    'annual_premium': 1481.55,
    'name': 'PruLife Return of Premium Term 30',
    'return_of_premium': true,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Best',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'transamerica',
    'carrier_name': 'Transamerica Life Insurance Company',
    'monthly_premium': 65.79,
    'annual_premium': 765.0,
    'name': 'Trendsetter Super 30',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Plus Non-Smoker',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'transamerica',
    'carrier_name': 'Transamerica Life Insurance Company',
    'monthly_premium': 70.0,
    'annual_premium': 814.0,
    'name': 'Trendsetter LB 30',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Plus Non-Smoker',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'lincoln-national-life',
    'carrier_name': 'Lincoln National Life Insurance Company',
    'monthly_premium': 71.58,
    'annual_premium': 818.0,
    'name': 'LifeElement (R) Level Term 30 (2014)',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Plus Non-tobacco',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'banner-life',
    'carrier_name': 'Banner Life Insurance Company',
    'monthly_premium': 60.86,
    'annual_premium': 695.57,
    'name': 'OPTerm 30 - 30 Year Term',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Plus Non-Tobacco',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'mutual-of-omaha',
    'carrier_name': 'United of Omaha Life Insurance Company',
    'monthly_premium': 59.37,
    'annual_premium': 678.5,
    'name': 'Term Life Answers 30',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Plus Non-Tobacco',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'principal-financial-group',
    'carrier_name': 'Principal National Life Insurance Co',
    'monthly_premium': 61.23,
    'annual_premium': 699.77,
    'name': '30-Year Term (2016)',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Super Preferred non-tobacco',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': true
  },
  {
    'carrier': 'protective',
    'carrier_name': 'Protective Life Insurance Company',
    'monthly_premium': 61.24,
    'annual_premium': 712.11,
    'name': 'Custom Choice UL - 30 Year No Lapse',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Select Preferred Non-Tobacco',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'sbli',
    'carrier_name': 'Savings Bank Life Insurance Co of MA',
    'monthly_premium': 60.52,
    'annual_premium': 695.59,
    'name': 'T-30/30 - 30 Year Term',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Plus Non-Nicotine',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'accordia',
    'carrier_name': 'Accordia Life and Annuity Company',
    'monthly_premium': 73.96,
    'annual_premium': 831.0,
    'name': '30-Year Level Premium Term',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Premier Non-Tobacco',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'minnesota',
    'carrier_name': 'Minnesota Life Insurance Company',
    'monthly_premium': 64.42,
    'annual_premium': 732.0,
    'name': 'Advantage Elite Select Life - 30 Year',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Select Non-Tobacco',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'minnesota',
    'carrier_name': 'Minnesota Life Insurance Company',
    'monthly_premium': 66.35,
    'annual_premium': 753.96,
    'name': 'Advantage Elite - 30 Year  (w/ext conv.)',
    'return_of_premium': false,
    'underwriting_class': 'preferred_plus',
    'health_category': 'Preferred Select Non-Tobacco',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  },
  {
    'carrier': 'metlife',
    'carrier_name': 'MetLife Insurance Company USA',
    'monthly_premium': 81.18,
    'annual_premium': 902.0,
    'name': 'Guaranteed Level Term 30',
    'return_of_premium': false,
    'underwriting_class': 'preferred',
    'health_category': 'Elite Nonsmoker',
    'coverage_amount': 700000,
    'term_in_years': 30,
    'table_rating': 0,
    'accelerated_underwriting': false
  }
];
